### ISSUE TITLE
메뉴 버튼 클릭이 안먹혀요!

### ISSUE THREAD

**Issue by thechunsik** [teampopong/popong.com#10]
이런 이슈 막 날려도 되나...용..

**Comment by e9t** [comment]
ㅋㅋㅋ 춘식님의 경우 PR 보내주시면 가장 좋지만...ㅋㅋ
어떤 버튼이 어떤 환경에서 안 먹히는지 좀 더 자세히 알려주실 수 있나요?

**Comment by thechunsik** [comment]
이게 파이어폭스에서만 발생하는 버그같은데... 메뉴에 anchor 로 a 링크들 잡아둔 것들이 안먹히네요! 요소검사에서 html을 아무거나 수정하고 나면 먹히는데..ㅋㅋㅋㅋ pr도 괜찮으면 저도 무슨 버그인지 한번 찾아볼게요!

**Comment by e9t** [comment]
아! 그러네요 저도 방금 확인했습니다. PR은 당연히 좋죠 ^^ 모든 오픈소스 개발자들에게 선물 같은거 아닌가요 ㅎ 언제든 무엇이든 감사히 받겠습니다~

**Comment by e9t** [comment]
모질라인이신 @thechunsik 님께서 훨씬 잘 아시겠지만, 어렵지 않게 해결할 수 있는 문제인 것 같네요. :) http://stackoverflow.com/a/21483457/1054939

**Comment by thechunsik** [comment]
아마 name attribute 로 해결하는? 내용같은데 브라우저 요소검사로 테스트를 해본 결과로는 메뉴에 있는 a태그 클릭할 때 클릭이벤트가 애초에 발생하지 않는것 같아요 뭐든 html 요소 아무거나 수정하고 나면 또 먹히고.... 잉?ㅋㅋㅋㅋ 파폭 버전업되면서 충돌하는건지....

**Comment by e9t** [comment]
위 링크에서 마지막 3번 문제였던 것 같아요 :)
춘식님 덕분에 버그가 또 잘 해결되었네요!

**Comment by thechunsik** [comment]
오호 흥미로운 버그가!! 다음엔 PR로 자체해결해보는걸로!ㅋㅋㅋ

**Comment by e9t** [comment]
:+1:
